// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NRkTUu1uVpXP_0wmwjuFpve3RcPMODA',
    appId: '1:952255180950:web:29377925c79e1f727292b7',
    messagingSenderId: '952255180950',
    projectId: 'viziobox-811a1',
    authDomain: 'viziobox-811a1.firebaseapp.com',
    storageBucket: 'viziobox-811a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCafa0ExttU2FfFpzUnh5i8uZL-wxXLv9s',
    appId: '1:952255180950:android:7257806e7669d8c57292b7',
    messagingSenderId: '952255180950',
    projectId: 'viziobox-811a1',
    storageBucket: 'viziobox-811a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYqXhNTQCJO6QnpsBZ5zPPgiOmga0J9w',
    appId: '1:952255180950:ios:c1bec9708573a8497292b7',
    messagingSenderId: '952255180950',
    projectId: 'viziobox-811a1',
    storageBucket: 'viziobox-811a1.firebasestorage.app',
    iosBundleId: 'com.viziobox.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLYqXhNTQCJO6QnpsBZ5zPPgiOmga0J9w',
    appId: '1:952255180950:ios:c1bec9708573a8497292b7',
    messagingSenderId: '952255180950',
    projectId: 'viziobox-811a1',
    storageBucket: 'viziobox-811a1.firebasestorage.app',
    iosBundleId: 'com.viziobox.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NRkTUu1uVpXP_0wmwjuFpve3RcPMODA',
    appId: '1:952255180950:web:ce77b7ac5315b90a7292b7',
    messagingSenderId: '952255180950',
    projectId: 'viziobox-811a1',
    authDomain: 'viziobox-811a1.firebaseapp.com',
    storageBucket: 'viziobox-811a1.firebasestorage.app',
  );
}
